print("Please enter five numbers.")
num_1 = float(input())
num_2 = float(input())
num_3 = float(input())
num_4 = float(input())
num_5 = float(input())
avg = (num_1 + num_2 + num_3 + num_4 + num_5)
print("The average of those numbers is:")
print("%.1f"%(avg/5))
